require 'spec_helper'

# Do not edit this file

describe CodingTest do
  it 'shows the day number with the smallest temperature spread' do
    expect(day_min_temp_spread('weather.dat')).to be == '14'
  end

  it 'shows the name of the team with the smallest point difference' do
    expect(team_min_point_spread('football.dat')).to be == 'Aston_Villa'
  end
end
